name: Test

on: push

jobs:
  test:
    timeout-minutes: 4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Build
        run: go build

      - name: Test
        run: go test ./... -covermode=atomic
